// Copyright 2023 squishyliquid (@squishyliquid)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define VIAL_TAP_DANCE_ENTRIES 16
#define VIAL_COMBO_ENTRIES 16
#define VIAL_KEY_OVERRIDE_ENTRIES 16
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define VIAL_ALT_REPEAT_KEY_ENTRIES 16

// #define DEBUG_MATRIX_SCAN_RATE //
#define ADC_RESOLUTION ADC_CFGR1_RES_12BIT

#define SERIAL_USART_DRIVER SD1    // USART 1
#define SERIAL_USART_TX_PIN A9
#define SERIAL_USART_RX_PIN A10
#define SERIAL_USART_TX_PAL_MODE 7
#define SERIAL_USART_RX_PAL_MODE 7
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_SPEED 2000000

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 4
#define BOOTMAGIC_ROW_RIGHT 5
#define BOOTMAGIC_COLUMN_RIGHT 7

#define MUX_BITS 3

#define ALL_MUX_PINS { B5, B6, B7 }

#define SPLIT_TRANSACTION_IDS_USER HE_CONFIG_SYNC
#define SPLIT_LAYER_STATE_ENABLE